- graphql/service/node/mutation_utils.go
- graphql/service/subscription/mutation_utils.go
> fix: removeNodes

- db/user.go
- graphql/mutation.go
- graphql/query.go
- graphql/root_schema.go
- graphql/schema_chains.go
- graphql/service/user/resolver.go
- graphql/service/user/schema.go
Add user profile allow user to
~~- [ ]    toggle dark theme~~
~~- [ ]     toggle between advanced mode and simple mode~~ (NO PLAN due to high client correlation)
Fix #8.
> feat: user features

- db/db.go
- go.mod
- go.sum
- Replace C  sqlite wrapper with pure Go sqlite.
> chore: replace c wrapper sqlite with pure go sqlite

- Makefile
- db/db.go
- go.mod
- go.sum
- pkg/sqlite/sqlite_mipsarch.go
- pkg/sqlite/sqlite_others.go
This PR fixes https://github.com/daeuniverse/dae-wing/issues/21.
```
CC=mips-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=mips go build .
```
> fix: use c sqlite3 wrapper for mips

- cmd/run.go
- dae/dae.go
- graphql/service/config/mutation_utils.go
Now, more info will be shown as following image if any failure:
> optimize: dump more assis log for 'run'

- graphql/service/dns/mutation_utils.go
- graphql/service/dns/resolver.go
- graphql/service/routing/mutation_utils.go
- graphql/service/routing/resolver.go
Fix #19.
1. Fix up updating routing.
2. Fix up updating dns.
3. Allow comments.
> fix: update routing and dns and allow using comments

- LICENSE
Add default license `AGPL-3.0-only`.
> chore: add license AGPL-3.0-only

- webrender/webrender.go
See https://github.com/daeuniverse/daed/actions/runs/5301403367/jobs/9595651657?pr=58#step:6:124
> fix(webrender): imported log but not used

- Makefile
- cmd/cmd.go
- cmd/export.go
- cmd/run.go
- db/app.go
- graphql/service/general/dae_resolver.go
- graphql/service/subscription/mutation_utils.go
1. Some links from `airports` cannot be accessed.
2. And our fetching has no timeout.
1. Add timeout 10 seconds for subscription fetching.
2. Add User-Agent:
```go
req.Header.Set("User-Agent", fmt.Sprintf("%v/%v (like v2rayA/1.0 WebRequestHelper) (like v2rayN/1.0 WebRequestHelper)", db.AppName, db.AppVersion))
```
3. Organize app variables into db directory.
> optimize: add User-Agent for subscription fetching

- cmd/run.go
- common/utils.go
No listening address printed after boot.
See the image:
This fix #39
> feat: add output of listening addresses

- Makefile
- db/app.go
- graphql/service/config/mutation_utils.go
The group with no node was ignored incorrectly.
Replenish all referenced groups.
> fix: incorrectly ignored empty group

- dae/utils.go
- graphql/service/config/mutation_utils.go
Outbounds `must_rules` and `must_xxx` are not supported.
This PR is to support it.
> fix: should support must_xxx and must_rules

- .github/sync-upstream.yml
Replicate https://github.com/daeuniverse/daed/blob/main/.github/workflows/sync-upstream.yml
Closes #60
> ci: add sync-upstream workflow

- .github/workflows/sync-upstream.yml
As the title suggests, ref to https://github.com/daeuniverse/ci-seed-jobs/pull/3
- ci(sync-upstream): update downstream workflow ref
NA
NA
> ci(sync-upstream): update downstream workflow ref

- .github/workflows/sync-upstream.yml
As the title suggests.
- ci(sync-upstream): fix invalid downstream workflow ref
NA
NA
> ci(sync-upstream): fix invalid downstream workflow ref

- dae/run.go
Problem: Always show this icon.
Hard to reproduce. This fix is a try.
> fix: potential stuck in reloading status

- graphql/service/config/mutation_utils.go
> chore/fix: unmatched annotations length

- db/system.go
- graphql/service/config/mutation_utils.go
- graphql/service/general/dae_resolver.go
> fix: unchangable `modified` status

- dae/run.go
- dae/utils.go
- go.mod
- go.sum
After daed started, the WAN interface were not up yet in some cases. This caused daed cannot find WAN interface.
This PR fixes it.
> fix: should wait for network for wan ready

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/proposal.yml
- .github/ISSUE_TEMPLATE/support-request.yml
Replicate https://github.com/daeuniverse/dae/pull/267
Use new issue_templates.
Preview: https://github.com/daeuniverse/dae-1/issues/new/choose
- chore/refactor: rework issue_templates
> chore/refactor: rework issue_templates

- .github/PULL_REQUEST_TEMPLATE.md
Update pr_template section headers.
> chore(pr_template): update section headers

- Makefile
> chore: add -buildmode=pie

- Makefile
> chore/fix(Makefile): fix recursive LDFLAGS reference

- CODEOWNERS
Set @daeuniverse/governance as default owner
> chore(codeowners): set @daeuniverse/governance as default owner

- Makefile
The compilation of ```daed``` failed.
> Makefile: LDFLAGS -> GO_LDFLAGS

- graphql/mutation.go
- graphql/root_schema.go
- graphql/service/node/mutation_utils.go
Support `updateNode`
https://t.me/daeuniverse/37548
Updating succeeded.
> feat: support `updateNode`

- Makefile
PRs that introduce `breaking changes`:
- https://github.com/daeuniverse/dae-wing/pull/96
- https://github.com/daeuniverse/dae-wing/pull/102
- https://github.com/daeuniverse/dae-wing/pull/104
- hotfix(makefile): completely demise buildarg=pie
> hotfix(makefile): completely demise buildarg=pie

- graphql/service/config/mutation_utils.go
> chore: the group policy is fixed can only have one node
